# --------------------------------------
# Author: Andreas Alfons
#         Erasmus Universiteit Rotterdam
# --------------------------------------

#' (Robustly) fit a mediation model
#'
#' (Robustly) estimate the effects in a mediation model.
#'
#' If \code{method} is \code{"regression"} and \code{robust} is \code{TRUE}
#' (the default), the effects are estimated via robust regressions with
#' \code{\link[robustbase]{lmrob}}.
#'
#' If \code{method} is \code{"covariance"} and \code{robust} is \code{TRUE},
#' the effects are estimated based on a Huber M-estimator of location and
#' scatter.  Note that this covariance-based approach is less robust than the
#' regression-based one described above.
#'
#' @aliases print.fit_mediation summary.reg_fit_mediation
#' summary.cov_fit_mediation
#'
#' @param data  a data frame containing the variables.
#' @param x  a character string, an integer or a logical vector specifying the
#' column of \code{data} containing the independent variable.
#' @param y  a character string, an integer or a logical vector specifying the
#' column of \code{data} containing the dependent variable.
#' @param m  a character string, an integer or a logical vector specifying the
#' column of \code{data} containing the hypothesized mediator variable.
#' @param covariates  optional; a character, integer or logical vector
#' specifying the columns of \code{data} containing additional covariates to be
#' used as control variables.
#' @param method  a character string specifying the method of
#' estimation.  Possible values are \code{"regression"} (the default)
#' to estimate the effects via regressions, or \code{"covariance"} to
#' estimate the effects via the covariance matrix.  Note that the effects are
#' always estimated via regressions if control variables are specified via
#' \code{covariates}.
#' @param robust  a logical indicating whether to robustly estimate the effects
#' (defaults to \code{TRUE}).
#' @param control  if \code{robust} is \code{TRUE} and \code{method} is
#' \code{"regression"}, a list of tuning parameters for
#' \code{\link[robustbase]{lmrob}} as generated by
#' \code{\link{reg_control}}.  If \code{robust} is \code{TRUE}
#' and \code{method} is \code{"covariance"}, a list of tuning parameters for
#' \code{\link{cov_Huber}} as generated by \code{\link{cov_control}}.
#' @param \dots  additional arguments can be used to specify tuning parameters
#' directly instead of via \code{control}.
#'
#' @return An object inheriting from class \code{"fit_mediation"} (class
#' \code{"reg_fit_mediation"} if \code{method} is \code{"regression"} or
#' \code{"cov_fit_mediation"} if \code{method} is \code{"covariance"}) with
#' the following components:
#' \item{a}{numeric; the point estimate of the effect of the independent
#' variable on the proposed mediator variable.}
#' \item{b}{numeric; the point estimate of the direct effect of the
#' proposed mediator variable on the dependent variable.}
#' \item{c}{numeric; the point estimate of the direct effect of the
#' independent variable on the dependent variable.}
#' \item{c_prime}{numeric; the point estimate of the total effect of the
#' independent variable on the dependent variable.}
#' \item{robust}{a logical indicating whether the effects were estimated
#' robustly.}
#' \item{fit_mx}{an object of class \code{"\link[robustbase]{lmrob}"} or
#' \code{"\link[stats]{lm}"} containing the estimation results from the
#' regression of the proposed mediator variable on the independent variable
#' (only \code{"reg_fit_mediation"}).}
#' \item{fit_ymx}{an object of class \code{"\link[robustbase]{lmrob}"} or
#' \code{"\link[stats]{lm}"} containing the estimation results from the
#' regression of the dependent variable on the proposed mediator and
#' independent variables (only \code{"reg_fit_mediation"}).}
#' \item{cov}{an object of class \code{"\link{cov_Huber}"} or
#' \code{"\link{cov_ML}"} containing the covariance matrix estimates
#' (only \code{"cov_fit_mediation"}).}
#' \item{data}{a data frame containing the independent, dependent and
#' proposed mediator variables.}
#'
#' @author Andreas Alfons
#'
#' @references
#' Zu, J. and Yuan, K.-H. (2010) Local influence and robust procedures for
#' mediation analysis. \emph{Multivariate Behavioral Research}, \bold{45}(1),
#' 1--44.
#'
#' @seealso \code{\link{test_mediation}}
#'
#' \code{\link[robustbase]{lmrob}}, \code{\link[stats]{lm}},
#' \code{\link{cov_Huber}}, \code{\link{cov_ML}}
#'
#' @examples
#' # control parameters
#' n <- 250             # number of observations
#' a <- b <- c <- 0.2   # true effects
#' t <- 10              # number of observations to contaminate
#'
#' # draw clean observations
#' set.seed(20160911)
#' x <- rnorm(n)
#' m <- a * x + rnorm(n)
#' y <- b * m + c * x + rnorm(n)
#'
#' # contaminate the first t observations
#' m[1:t] <- m[1:t] - 6
#' y[1:t] <- y[1:t] + 6
#'
#' # construct data frame
#' data <- data.frame(x, y, m)
#'
#' # fit mediation model
#' fit_mediation(data, "x", "y", "m")
#'
#' @keywords multivariate
#'
#' @import boot
#' @import robustbase
#' @export

fit_mediation <- function(data, x, y, m, covariates = NULL,
                          method = c("regression", "covariance"),
                          robust = TRUE, control, ...) {
  ## initializations
  # prepare data set
  data <- as.data.frame(data)
  x <- data[, x, drop=FALSE]
  y <- data[, y, drop=FALSE]
  m <- data[, m, drop=FALSE]
  covariates <- data[, covariates, drop=FALSE]
  data <- cbind(x, y, m, covariates)
  # extract names
  cn <- names(data)
  x <- cn[1]
  y <- cn[2]
  m <- cn[3]
  covariates <- cn[-(1:3)]
  # make sure that variables are numeric
  convert <- !sapply(data, is.numeric)
  data[convert] <- lapply(data[convert], as.numeric)
  # remove incomplete observations
  data <- data[complete.cases(data), ]
  # check if there are enough observations
  n <- nrow(data)
  if(n <= 3) stop("not enough observations")
  # check other arguments
  method <- match.arg(method)
  if(length(covariates) > 0 && method == "covariance") {
    method <- "regression"
    warning("using regression method")
  }
  robust <- isTRUE(robust)
  if(robust && missing(control)) {
    if(method == "regression") control <- reg_control(...)
    else control <- cov_control(...)
  }
  ## estimate effects
  if(method == "regression") {
    reg_fit_mediation(x, y, m, covariates, data=data,
                      robust=robust, control=control)
  } else cov_fit_mediation(x, y, m, data=data, robust=robust, control=control)
}


## estimate the effects in a mediation model via regressions
reg_fit_mediation <- function(x, y, m, covariates = character(), data,
                              robust = TRUE, control = reg_control()) {
  # construct formulas for regression models
  covariate_term <- paste(c("", covariates), collapse="+")
  f_mx <- as.formula(paste(m, "~", x, covariate_term, sep=""))
  f_ymx <- as.formula(paste(y, "~", m, "+", x, covariate_term, sep=""))
  # compute regression models
  if(robust) {
    # for the robust method, the total effect is estimated as c' = ab + c
    # to satisfy this relationship
    fit_mx <- lmrob(f_mx, data=data, control=control, model=FALSE, x=FALSE)
    fit_ymx <- lmrob(f_ymx, data=data, control=control, model=FALSE, x=FALSE)
    fit_yx <- NULL
  } else {
    # for the standard method, there is not much additional cost in performing
    # the regression for the total effect
    fit_mx <- lm(f_mx, data=data, model=FALSE)
    fit_ymx <- lm(f_ymx, data=data, model=FALSE)
    f_yx <- as.formula(paste(y, "~", x, covariate_term, sep=""))
    fit_yx <- lm(f_yx, data=data, model=FALSE)
  }
  # extract effects
  a <- unname(coef(fit_mx)[2])
  b <- unname(coef(fit_ymx)[2])
  c <- unname(coef(fit_ymx)[3])
  if(robust) c_prime <- a*b + c
  else c_prime <- unname(coef(fit_yx)[2])
  # return results
  result <- list(a=a, b=b, c=c, c_prime=c_prime, fit_mx=fit_mx, fit_ymx=fit_ymx,
                 fit_yx=fit_yx, x=x, y=y, m=m, covariates=covariates,
                 data=data, robust=robust)
  if(robust) result$control <- control
  class(result) <- c("reg_fit_mediation", "fit_mediation")
  result
}


## estimate the effects in a mediation model via the covariance matrix
cov_fit_mediation <- function(x, y, m, data, robust = TRUE,
                              control = cov_control()) {
  # compute scatter matrix (Huber M-estimator or MLE of covariance matrix)
  cov <- if(robust) cov_Huber(data, control=control) else cov_ML(data)
  S <- cov$cov
  # compute coefficients of mediation model
  a <- S[m, x] / S[x, x]
  det <- S[x, x] * S[m, m] - S[m, x]^2
  b <- (-S[m, x] * S[y, x] + S[x, x] * S[y, m]) / det
  c <- (S[m, m] * S[y, x] - S[m, x] * S[y, m]) / det
  c_prime <- S[y, x] / S[x, x]
  # return results
  result <- list(a=a, b=b, c=c, c_prime=c_prime, cov=cov, x=x, y=y, m=m,
                 data=data, robust=robust)
  if(robust) result$control <- control
  class(result) <- c("cov_fit_mediation", "fit_mediation")
  result
}
