# --------------------------------------
# Author: Andreas Alfons
#         Erasmus Universiteit Rotterdam
# --------------------------------------

#' (Robust) mediation analysis
#'
#' Perform (robust) mediation analysis via a (fast and robust) bootstrap test
#' or Sobel's test.
#'
#' If \code{method} is \code{"regression"} and \code{robust} is \code{TRUE}
#' (the default), the tests are based on robust regressions with
#' \code{\link[robustbase]{lmrob}}.  The bootstrap test is thereby performed
#' via the fast and robust bootstrap.
#'
#' If \code{method} is \code{"covariance"} and \code{robust} is \code{TRUE},
#' the tests are based on a Huber M-estimator of location and scatter.  For the
#' bootstrap test, the M-estimates are used to first clean the data via a
#' transformation.  Then the standard bootstrap is performed with the cleaned
#' data.  Note that this covariance-based approach is less robust than the
#' regression-based one described above.  Furthermore, the bootstrap does not
#' account for the variability from cleaning the data.
#'
#' \code{robmed} is a wrapper function for performing robust mediation analysis
#' via regressions and the fast and robust bootstrap (inspired by our
#' \code{SPSS} macro \code{ROBMED}).
#'
#' \code{indirect} is a wrapper function for performing non-robust mediation
#' analysis via regressions and the bootstrap (inspired by Preacher & Hayes'
#' \code{SPSS} macro \code{INDIRECT}).
#'
#' @aliases print.boot_test_mediation print.sobel_test_mediation
#'
#' @param data  a data frame containing the variables.  Alternatively, this can
#' be a mediation model fit as returned by \code{\link{fit_mediation}}.
#' @param x  a character string, an integer or a logical vector specifying the
#' column of \code{data} containing the independent variable.
#' @param y  a character string, an integer or a logical vector specifying the
#' column of \code{data} containing the dependent variable.
#' @param m  a character string, an integer or a logical vector specifying the
#' column of \code{data} containing the hypothesized mediator variable.
#' @param covariates  optional; a character, integer or logical vector
#' specifying the columns of \code{data} containing additional covariates to be
#' used as control variables.
#' @param test  a character string specifying the test to be performed for
#' the indirect effect.  Possible values are \code{"boot"} (the default) for
#' the bootstrap, or \code{"sobel"} for Sobel's test.
#' @param alternative  a character string specifying the alternative hypothesis
#' in the test for the indirect effect.  Possible values are \code{"twosided"}
#' (the default), \code{"less"} or \code{"greater"}.
#' @param R  an integer giving the number of bootstrap replicates.  The default
#' is to use 5000 bootstrap replicates.
#' @param level  numeric; the confidence level of the confidence interval in
#' the bootstrap test.  The default is to compute a 95\% confidence interval.
#' @param type  a character string specifying the type of confidence interval
#' to be computed in the bootstrap test.  Possible values are \code{"bca"} (the
#' default) for the bias-corrected and accelerated bootstrap, or \code{"perc"}
#' for the percentile bootstrap.
#' @param method  a character string specifying the method of estimation for
#' the mediation model.  Possible values are \code{"regression"} (the default)
#' to estimate the effects via regressions, or \code{"covariance"} to estimate
#' the effects via the covariance matrix.  Note that the effects are always
#' estimated via regressions if control variables are specified via
#' \code{covariates}.
#' @param robust  a logical indicating whether to perform a robust test
#' (defaults to \code{TRUE}).
#' @param control  if \code{robust} is \code{TRUE} and \code{method} is
#' \code{"regression"}, a list of tuning parameters for
#' \code{\link[robustbase]{lmrob}} as generated by
#' \code{\link{reg_control}}.  If \code{robust} is \code{TRUE}
#' and \code{method} is \code{"covariance"}, a list of tuning parameters for
#' \code{\link{cov_Huber}} as generated by \code{\link{cov_control}}.
#' @param \dots  additional arguments to be passed down.  For the bootstrap
#' tests, those can be used to specify arguments of \code{\link[boot]{boot}},
#' for example for parallel computing.
#'
#' @return An object inheriting from class \code{"test_mediation"} (class
#' \code{"boot_test_mediation"} if \code{test} is \code{"boot"} or
#' \code{"sobel_test_mediation"} if \code{test} is \code{"sobel"}) with the
#' following components:
#' \item{ab}{numeric; the point estimate of the indirect effect.}
#' \item{ci}{a numeric vector of length two containing the bootstrap
#' confidence interval for the indirect effect (only
#' \code{"boot_test_mediation"}).}
#' \item{reps}{an object of class \code{"\link[boot]{boot}"} containing
#' the bootstrap replicates of the indirect effect (only
#' \code{"boot_test_mediation"}).}
#' \item{se}{numeric; the standard error of the indirect effect according
#' to Sobel's formula (only \code{"sobel_test_mediation"}).}
#' \item{statistic}{numeric; the test statistic for Sobel's test (only
#' \code{"sobel_test_mediation"}).}
#' \item{p_value}{numeric; the p-Value from Sobel's test (only
#' \code{"sobel_test_mediation"}).}
#' \item{alternative}{a character string specifying the alternative
#' hypothesis in the test for the indirect effect.}
#' \item{R}{an integer giving the number of bootstrap replicates (only
#' \code{"boot_test_mediation"}).}
#' \item{level}{numeric; the confidence level of the bootstrap confidence
#' interval (only \code{"boot_test_mediation"}).}
#' \item{type}{a character string specifying the type of bootstrap
#' confidence interval (only \code{"boot_test_mediation"}).}
#' \item{fit}{an object inheriting from class
#' \code{"\link{fit_mediation}"} containing the estimation results for the
#' direct effect and the total effect in the mediation model.}
#'
#' @author Andreas Alfons
#'
#' @references
#' Preacher, K.J. and Hayes, A.F. (2004) SPSS and SAS procedures for estimating
#' indirect effects in simple mediation models. \emph{Behavior Research Methods,
#' Instruments, & Computers}, \bold{36}(4), 717--731.
#'
#' Salibian-Barrera, M. and Zamar, R. (2002) Bootstrapping robust estimates of
#' regression. \emph{The Annals of Statistics}, \bold{30}(2), 556--582.
#'
#' Sobel, M.E. (1982) Asymptotic confidence intervals for indirect effects in
#' structural equation models. \emph{Sociological Methodology}, \bold{13},
#' 290--312.
#'
#' Zu, J. and Yuan, K.-H. (2010) Local influence and robust procedures for
#' mediation analysis. \emph{Multivariate Behavioral Research}, \bold{45}(1),
#' 1--44.
#'
#' @seealso \code{\link{fit_mediation}}
#'
#' \code{\link[=coef.test_mediation]{coef}},
#' \code{\link[=confint.test_mediation]{confint}},
#' \code{\link[=fortify.test_mediation]{fortify}} and
#' \code{\link[=plot_mediation]{plot}} methods
#'
#' \code{\link[boot]{boot}}, \code{\link[robustbase]{lmrob}},
#' \code{\link[stats]{lm}}, \code{\link{cov_Huber}}, \code{\link{cov_ML}}
#'
#' @examples
#' # control parameters
#' n <- 250             # number of observations
#' a <- b <- c <- 0.2   # true effects
#' t <- 10              # number of observations to contaminate
#'
#' # draw clean observations
#' set.seed(20160911)
#' x <- rnorm(n)
#' m <- a * x + rnorm(n)
#' y <- b * m + c * x + rnorm(n)
#'
#' # contaminate the first t observations
#' m[1:t] <- m[1:t] - 6
#' y[1:t] <- y[1:t] + 6
#'
#' # construct data frame
#' data <- data.frame(x, y, m)
#'
#' # perform mediation analysis
#' test <- test_mediation(data, "x", "y", "m")
#' summary(test)
#'
#' @keywords multivariate
#'
#' @import boot
#' @import robustbase
#' @export

test_mediation <- function(data, ...) UseMethod("test_mediation")


#' @rdname test_mediation
#' @method test_mediation default
#' @export

test_mediation.default <- function(data, x, y, m, covariates = NULL,
                                   test = c("boot", "sobel"),
                                   alternative = c("twosided", "less", "greater"),
                                   R = 5000, level = 0.95,
                                   type = c("bca", "perc"),
                                   method = c("regression", "covariance"),
                                   robust = TRUE, control, ...) {
  ## fit mediation model
  fit <- fit_mediation(data, x=x, y=y, m=m, covariates=covariates,
                       method=method, robust=robust, control=control)
  ## call method for fitted model
  test_mediation(fit, test=test, alternative=alternative,
                 R=R, level=level, type=type, ...)
}


#' @rdname test_mediation
#' @method test_mediation fit_mediation
#' @export

test_mediation.fit_mediation <- function(data, test = c("boot", "sobel"),
                                         alternative = c("twosided", "less", "greater"),
                                         R = 5000, level = 0.95,
                                         type = c("bca", "perc"),
                                         ...) {
  ## initializations
  test <- match.arg(test)
  alternative <- match.arg(alternative)
  ## perform mediation analysis
  if(test == "boot") {
    # further inizializations
    level <- rep(as.numeric(level), length.out=1)
    if(is.na(level) || level < 0 || level > 1) level <- formals()$level
    type <- match.arg(type)
    # perform bootstrap test
    boot_test_mediation(data, alternative=alternative, R=R,
                        level=level, type=type, ...)
  } else if(test == "sobel") {
    # perform Sobel test
    sobel_test_mediation(data, alternative=alternative)
  } else stop("test not implemented")
}


#' @rdname test_mediation
#' @export

robmed <- function(..., test = "boot", method = "regression",
                   robust = TRUE) {
  test_mediation(..., test="boot", method="regression", robust=TRUE)
}


#' @rdname test_mediation
#' @export

indirect <- function(..., test = "boot", method = "regression",
                     robust = FALSE) {
  test_mediation(..., test="boot", method="regression", robust=FALSE)
}


## internal function for bootstrap test
boot_test_mediation <- function(fit,
                                alternative = c("twosided", "less", "greater"),
                                R = 5000, level = 0.95, type = c("bca", "perc"),
                                ...) {
  if(inherits(fit, "reg_fit_mediation")) {
    # indices of covariates in data matrix to be used in bootstrap
    j <- match(fit$covariates, names(fit$data)) + 1
    n <- nrow(fit$data)
    # check if fast and robust bootstrap should be applied
    if(fit$robust) {
      # extract regression models
      fit_mx <- fit$fit_mx
      fit_ymx <- fit$fit_ymx
      # extract (square root of) robustness weights and combine data
      w_m <- sqrt(weights(fit_mx, type="robustness"))
      w_y <- sqrt(weights(fit_ymx, type="robustness"))
      z <- cbind(rep.int(1, n), as.matrix(fit$data), w_m, w_y)
      # compute matrices for linear corrections
      psi_control <- get_psi_control(fit_mx)  # the same for both model fits
      corr_m <- correction_matrix(z[, c(1:2, j)], weights=w_m,
                                  residuals=residuals(fit_mx),
                                  scale=fit_mx$scale,
                                  control=psi_control)
      coef_m <- coef(fit_mx)
      corr_y <- correction_matrix(z[, c(1, 4, 2, j)], weights=w_y,
                                  residuals=residuals(fit_ymx),
                                  scale=fit_ymx$scale,
                                  control=psi_control)
      coef_y <- coef(fit_ymx)
      # perform fast and robust bootstrap
      bootstrap <- local_boot(z, function(z, i, corr_m, coef_m, corr_y, coef_y) {
        # extract bootstrap sample from the data
        z_i <- z[i, , drop=FALSE]
        w_m_i <- z_i[, "w_m"]
        w_y_i <- z_i[, "w_y"]
        # check whether there are enough observations with nonzero weights
        if(sum(w_m_i > 0) <= 2 || sum(w_y_i > 0) <= 3) return(NA)
        # compute coefficients from weighted regression m ~ x + covariates
        weighted_x_i <- w_m_i * z_i[, c(1:2, j)]
        weighted_m_i <- w_m_i * z_i[, 4]
        coef_m_i <- solve(crossprod(weighted_x_i)) %*%
          crossprod(weighted_x_i, weighted_m_i)
        # compute coefficients from weighted regression y ~ m + x + covariates
        weighted_mx_i <- w_y_i * z_i[, c(1, 4, 2, j)]
        weighted_y_i <- w_y_i * z_i[, 3]
        coef_y_i <- solve(crossprod(weighted_mx_i)) %*%
          crossprod(weighted_mx_i, weighted_y_i)
        # compute corrected coefficients
        coef_m_i <- drop(coef_m + corr_m %*% (coef_m_i - coef_m))
        coef_y_i <- drop(coef_y + corr_y %*% (coef_y_i - coef_y))
        # compute effects
        a <- unname(coef_m_i[2])
        b <- unname(coef_y_i[2])
        c <- unname(coef_y_i[3])
        ab <- a * b
        c_prime <- ab + c
        # compute effects of control variables if they exist
        covariates <- unname(coef_y_i[-(1:3)])
        # return effects
        c(ab, a, b, c, c_prime, covariates)
      }, R=R, corr_m=corr_m, coef_m=coef_m, corr_y=corr_y, coef_y=coef_y, ...)
      R <- colSums(!is.na(bootstrap$t))  # adjust number of replicates for NAs
    } else {
      # combine data
      z <- cbind(rep.int(1, n), as.matrix(fit$data))
      # perform bootstrap
      bootstrap <- local_boot(z, function(z, i) {
        # extract bootstrap sample from the data
        z_i <- z[i, , drop=FALSE]
        # compute coefficients from regression m ~ x + covariates
        x_i <- z_i[, c(1:2, j)]
        m_i <- z_i[, 4]
        coef_m_i <- drop(solve(crossprod(x_i)) %*% crossprod(x_i, m_i))
        # compute coefficients from regression y ~ m + x + covariates
        mx_i <- z_i[, c(1, 4, 2, j)]
        y_i <- z_i[, 3]
        coef_y_i <- drop(solve(crossprod(mx_i)) %*% crossprod(mx_i, y_i))
        # compute effects
        unname(coef_m_i[2]) * unname(coef_y_i[2])
        a <- unname(coef_m_i[2])
        b <- unname(coef_y_i[2])
        c <- unname(coef_y_i[3])
        ab <- a * b
        c_prime <- ab + c
        # compute effects of control variables if they exist
        covariates <- unname(coef_y_i[-(1:3)])
        # return effects
        c(ab, a, b, c, c_prime, covariates)
      }, R=R, ...)
      R <- nrow(bootstrap$t)  # make sure that number of replicates is correct
    }
  } else if(inherits(fit, "cov_fit_mediation")) {
    # extract data and variable names
    x <- fit$x
    y <- fit$y
    m <- fit$m
    data <- fit$data
    # check if the robust transformation of Zu & Yuan (2010) should be applied
    if(fit$robust) {
      cov <- fit$cov
      data[] <- mapply("-", data, cov$center, SIMPLIFY=FALSE, USE.NAMES=FALSE)
      data <- weights(cov, type="consistent") * data
    }
    # perform bootstrap
    bootstrap <- local_boot(data, function(z, i) {
      # extract bootstrap sample from the data
      z_i <- z[i, , drop=FALSE]
      # compute MLE of covariance matrix on bootstrap sample
      S <- cov_ML(z_i)$cov
      # compute effects
      a <- S[m, x] / S[x, x]
      det <- S[x, x] * S[m, m] - S[m, x]^2
      b <- (-S[m, x] * S[y, x] + S[x, x] * S[y, m]) / det
      c <- (S[m, m] * S[y, x] - S[m, x] * S[y, m]) / det
      c_prime <- S[y, x] / S[x, x]
      c(a*b, a, b, c, c_prime)
    }, R=R, ...)
    R <- nrow(bootstrap$t)  # make sure that number of replicates is correct
  } else stop("method not implemented")
  # extract confidence interval for indirect effect
  ci <- confint(bootstrap, parm=1, level=level, alternative=alternative,
                type=type)
  # construct return object
  result <- list(ab=mean(bootstrap$t[, 1], na.rm=TRUE), ci=ci, reps=bootstrap,
                 alternative=alternative, R=R[1], level=level, type=type,
                 fit=fit)
  class(result) <- c("boot_test_mediation", "test_mediation")
  result
}

## internal function for sobel test
sobel_test_mediation <- function(fit,
                                 alternative = c("twosided", "less", "greater"),
                                 ...) {
  # extract coefficients
  a <- fit$a
  b <- fit$b
  # compute standard errors
  summary <- get_summary(fit)
  sa <- summary$a[1, 2]
  sb <- summary$b[1, 2]
  # compute test statistic and p-Value
  ab <- a * b
  se <- sqrt(b^2 * sa^2 + a^2 * sb^2)
  z <- ab / se
  p_value <- p_value_z(z, alternative=alternative)
  # construct return item
  result <- list(ab=ab, se=se, statistic=z, p_value=p_value,
                 alternative=alternative, fit=fit)
  class(result) <- c("sobel_test_mediation", "test_mediation")
  result
}

# ## wrapper function for boot() that ignores unused arguments, but allows
# ## arguments for parallel computing to be passed down
# local_boot <- function(..., sim, stype, L, m, ran.gen, mle) boot(...)

## get control arguments for psi function as used in a given model fit
get_psi_control <- function(object) object$control[c("tuning.psi", "psi")]

## compute matrix for linear correction
correction_matrix <- function(X, weights, residuals, scale, control) {
  tmp <- Mpsi(residuals/scale, cc=control$tuning.psi, psi=control$psi, deriv=1)
  solve(crossprod(X, tmp * X)) %*% crossprod(weights * X)
}

## internal function to compute p-value based on normal distribution
p_value_z <- function(z, alternative = c("twosided", "less", "greater")) {
  # initializations
  alternative <- match.arg(alternative)
  # compute p-value
  switch(alternative, twosided=2*pnorm(abs(z), lower.tail=FALSE),
         less=pnorm(z), greater=pnorm(z, lower.tail=FALSE))
}
